// Code generated by counterfeiter. DO NOT EDIT.
package resolverfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph/shared/configmaps"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/graph/shared/secrets"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/resolver"
	"k8s.io/apimachinery/pkg/types"
)

type FakeResolver struct {
	GetConfigMapsStub        func() map[types.NamespacedName]*configmaps.CaCertConfigMap
	getConfigMapsMutex       sync.RWMutex
	getConfigMapsArgsForCall []struct {
	}
	getConfigMapsReturns struct {
		result1 map[types.NamespacedName]*configmaps.CaCertConfigMap
	}
	getConfigMapsReturnsOnCall map[int]struct {
		result1 map[types.NamespacedName]*configmaps.CaCertConfigMap
	}
	GetSecretsStub        func() map[types.NamespacedName]*secrets.Secret
	getSecretsMutex       sync.RWMutex
	getSecretsArgsForCall []struct {
	}
	getSecretsReturns struct {
		result1 map[types.NamespacedName]*secrets.Secret
	}
	getSecretsReturnsOnCall map[int]struct {
		result1 map[types.NamespacedName]*secrets.Secret
	}
	ResolveStub        func(resolver.ResourceType, types.NamespacedName) error
	resolveMutex       sync.RWMutex
	resolveArgsForCall []struct {
		arg1 resolver.ResourceType
		arg2 types.NamespacedName
	}
	resolveReturns struct {
		result1 error
	}
	resolveReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeResolver) GetConfigMaps() map[types.NamespacedName]*configmaps.CaCertConfigMap {
	fake.getConfigMapsMutex.Lock()
	ret, specificReturn := fake.getConfigMapsReturnsOnCall[len(fake.getConfigMapsArgsForCall)]
	fake.getConfigMapsArgsForCall = append(fake.getConfigMapsArgsForCall, struct {
	}{})
	stub := fake.GetConfigMapsStub
	fakeReturns := fake.getConfigMapsReturns
	fake.recordInvocation("GetConfigMaps", []interface{}{})
	fake.getConfigMapsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeResolver) GetConfigMapsCallCount() int {
	fake.getConfigMapsMutex.RLock()
	defer fake.getConfigMapsMutex.RUnlock()
	return len(fake.getConfigMapsArgsForCall)
}

func (fake *FakeResolver) GetConfigMapsCalls(stub func() map[types.NamespacedName]*configmaps.CaCertConfigMap) {
	fake.getConfigMapsMutex.Lock()
	defer fake.getConfigMapsMutex.Unlock()
	fake.GetConfigMapsStub = stub
}

func (fake *FakeResolver) GetConfigMapsReturns(result1 map[types.NamespacedName]*configmaps.CaCertConfigMap) {
	fake.getConfigMapsMutex.Lock()
	defer fake.getConfigMapsMutex.Unlock()
	fake.GetConfigMapsStub = nil
	fake.getConfigMapsReturns = struct {
		result1 map[types.NamespacedName]*configmaps.CaCertConfigMap
	}{result1}
}

func (fake *FakeResolver) GetConfigMapsReturnsOnCall(i int, result1 map[types.NamespacedName]*configmaps.CaCertConfigMap) {
	fake.getConfigMapsMutex.Lock()
	defer fake.getConfigMapsMutex.Unlock()
	fake.GetConfigMapsStub = nil
	if fake.getConfigMapsReturnsOnCall == nil {
		fake.getConfigMapsReturnsOnCall = make(map[int]struct {
			result1 map[types.NamespacedName]*configmaps.CaCertConfigMap
		})
	}
	fake.getConfigMapsReturnsOnCall[i] = struct {
		result1 map[types.NamespacedName]*configmaps.CaCertConfigMap
	}{result1}
}

func (fake *FakeResolver) GetSecrets() map[types.NamespacedName]*secrets.Secret {
	fake.getSecretsMutex.Lock()
	ret, specificReturn := fake.getSecretsReturnsOnCall[len(fake.getSecretsArgsForCall)]
	fake.getSecretsArgsForCall = append(fake.getSecretsArgsForCall, struct {
	}{})
	stub := fake.GetSecretsStub
	fakeReturns := fake.getSecretsReturns
	fake.recordInvocation("GetSecrets", []interface{}{})
	fake.getSecretsMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeResolver) GetSecretsCallCount() int {
	fake.getSecretsMutex.RLock()
	defer fake.getSecretsMutex.RUnlock()
	return len(fake.getSecretsArgsForCall)
}

func (fake *FakeResolver) GetSecretsCalls(stub func() map[types.NamespacedName]*secrets.Secret) {
	fake.getSecretsMutex.Lock()
	defer fake.getSecretsMutex.Unlock()
	fake.GetSecretsStub = stub
}

func (fake *FakeResolver) GetSecretsReturns(result1 map[types.NamespacedName]*secrets.Secret) {
	fake.getSecretsMutex.Lock()
	defer fake.getSecretsMutex.Unlock()
	fake.GetSecretsStub = nil
	fake.getSecretsReturns = struct {
		result1 map[types.NamespacedName]*secrets.Secret
	}{result1}
}

func (fake *FakeResolver) GetSecretsReturnsOnCall(i int, result1 map[types.NamespacedName]*secrets.Secret) {
	fake.getSecretsMutex.Lock()
	defer fake.getSecretsMutex.Unlock()
	fake.GetSecretsStub = nil
	if fake.getSecretsReturnsOnCall == nil {
		fake.getSecretsReturnsOnCall = make(map[int]struct {
			result1 map[types.NamespacedName]*secrets.Secret
		})
	}
	fake.getSecretsReturnsOnCall[i] = struct {
		result1 map[types.NamespacedName]*secrets.Secret
	}{result1}
}

func (fake *FakeResolver) Resolve(arg1 resolver.ResourceType, arg2 types.NamespacedName) error {
	fake.resolveMutex.Lock()
	ret, specificReturn := fake.resolveReturnsOnCall[len(fake.resolveArgsForCall)]
	fake.resolveArgsForCall = append(fake.resolveArgsForCall, struct {
		arg1 resolver.ResourceType
		arg2 types.NamespacedName
	}{arg1, arg2})
	stub := fake.ResolveStub
	fakeReturns := fake.resolveReturns
	fake.recordInvocation("Resolve", []interface{}{arg1, arg2})
	fake.resolveMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeResolver) ResolveCallCount() int {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	return len(fake.resolveArgsForCall)
}

func (fake *FakeResolver) ResolveCalls(stub func(resolver.ResourceType, types.NamespacedName) error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = stub
}

func (fake *FakeResolver) ResolveArgsForCall(i int) (resolver.ResourceType, types.NamespacedName) {
	fake.resolveMutex.RLock()
	defer fake.resolveMutex.RUnlock()
	argsForCall := fake.resolveArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeResolver) ResolveReturns(result1 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	fake.resolveReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeResolver) ResolveReturnsOnCall(i int, result1 error) {
	fake.resolveMutex.Lock()
	defer fake.resolveMutex.Unlock()
	fake.ResolveStub = nil
	if fake.resolveReturnsOnCall == nil {
		fake.resolveReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.resolveReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeResolver) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeResolver) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ resolver.Resolver = new(FakeResolver)
