// Code generated by counterfeiter. DO NOT EDIT.
package configfakes

import (
	"sync"
)

type FakeSecretStorer struct {
	GetJWTStub        func() []byte
	getJWTMutex       sync.RWMutex
	getJWTArgsForCall []struct {
	}
	getJWTReturns struct {
		result1 []byte
	}
	getJWTReturnsOnCall map[int]struct {
		result1 []byte
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSecretStorer) GetJWT() []byte {
	fake.getJWTMutex.Lock()
	ret, specificReturn := fake.getJWTReturnsOnCall[len(fake.getJWTArgsForCall)]
	fake.getJWTArgsForCall = append(fake.getJWTArgsForCall, struct {
	}{})
	stub := fake.GetJWTStub
	fakeReturns := fake.getJWTReturns
	fake.recordInvocation("GetJWT", []interface{}{})
	fake.getJWTMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSecretStorer) GetJWTCallCount() int {
	fake.getJWTMutex.RLock()
	defer fake.getJWTMutex.RUnlock()
	return len(fake.getJWTArgsForCall)
}

func (fake *FakeSecretStorer) GetJWTCalls(stub func() []byte) {
	fake.getJWTMutex.Lock()
	defer fake.getJWTMutex.Unlock()
	fake.GetJWTStub = stub
}

func (fake *FakeSecretStorer) GetJWTReturns(result1 []byte) {
	fake.getJWTMutex.Lock()
	defer fake.getJWTMutex.Unlock()
	fake.GetJWTStub = nil
	fake.getJWTReturns = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSecretStorer) GetJWTReturnsOnCall(i int, result1 []byte) {
	fake.getJWTMutex.Lock()
	defer fake.getJWTMutex.Unlock()
	fake.GetJWTStub = nil
	if fake.getJWTReturnsOnCall == nil {
		fake.getJWTReturnsOnCall = make(map[int]struct {
			result1 []byte
		})
	}
	fake.getJWTReturnsOnCall[i] = struct {
		result1 []byte
	}{result1}
}

func (fake *FakeSecretStorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getJWTMutex.RLock()
	defer fake.getJWTMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSecretStorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
