apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: external-gateway
spec:
  gatewayClassName: nginx
  infrastructure:
    parametersRef:
      group: gateway.nginx.org
      kind: NginxProxy
      name: external-nginx-config
  listeners:
  - name: http
    port: 80
    protocol: HTTP
    allowedRoutes:
      namespaces:
        from: All
  - name: tls
    port: 443
    protocol: TLS
    tls:
      mode: Passthrough
    allowedRoutes:
      namespaces:
        from: All

---
apiVersion: gateway.nginx.org/v1alpha2
kind: NginxProxy
metadata:
  name: external-nginx-config
spec:
  dnsResolver:
    addresses:
    - type: IPAddress
      value: "8.8.8.8"
    - type: IPAddress
      value: "1.1.1.1"
    timeout: "30s"
    cacheTTL: "60s"
    disableIPv6: false
