#!/usr/bin/env bash

set -e

source "${HOME}"/vars.env

cd nginx-gateway-fabric/tests && make .vm-gatewaylink-test CI=${CI} TAG="${TAG}" PREFIX="${PREFIX}" \
    NGINX_PREFIX="${NGINX_PREFIX}" NGINX_PLUS_PREFIX="${NGINX_PLUS_PREFIX}" PLUS_ENABLED="${PLUS_ENABLED}" \
    GINKGO_FLAGS="${GINKGO_FLAGS}" PULL_POLICY=Always GW_SERVICE_TYPE=LoadBalancer NGF_VERSION="${NGF_VERSION}" \
    PLUS_USAGE_ENDPOINT="${PLUS_USAGE_ENDPOINT}" GKE_PROJECT="${GKE_PROJECT}" \
    BIGIP_MGMT_PORT="${BIGIP_MGMT_PORT:-8443}" BIGIP_VIP="${BIGIP_VIP}" BIGIP_PARTITION="${BIGIP_PARTITION}" \
    BIGIP_USERNAME="${BIGIP_USERNAME}" BIGIP_PASSWORD="${BIGIP_PASSWORD}" \
    GATEWAYLINK_LABEL="${GATEWAYLINK_LABEL:-gatewaylink}" IPAM_RANGE="${IPAM_RANGE}"
