// Code generated by counterfeiter. DO NOT EDIT.
package statusfakes

import (
	"context"
	"sync"

	"github.com/go-logr/logr"
	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/status"
)

type FakeGroupUpdater struct {
	UpdateGroupStub        func(context.Context, logr.Logger, string, ...status.UpdateRequest)
	updateGroupMutex       sync.RWMutex
	updateGroupArgsForCall []struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 string
		arg4 []status.UpdateRequest
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeGroupUpdater) UpdateGroup(arg1 context.Context, arg2 logr.Logger, arg3 string, arg4 ...status.UpdateRequest) {
	var arg4Copy []status.UpdateRequest
	if arg4 != nil {
		arg4Copy = make([]status.UpdateRequest, len(arg4))
		copy(arg4Copy, arg4)
	}
	fake.updateGroupMutex.Lock()
	fake.updateGroupArgsForCall = append(fake.updateGroupArgsForCall, struct {
		arg1 context.Context
		arg2 logr.Logger
		arg3 string
		arg4 []status.UpdateRequest
	}{arg1, arg2, arg3, arg4Copy})
	stub := fake.UpdateGroupStub
	fake.recordInvocation("UpdateGroup", []interface{}{arg1, arg2, arg3, arg4Copy})
	fake.updateGroupMutex.Unlock()
	if stub != nil {
		fake.UpdateGroupStub(arg1, arg2, arg3, arg4...)
	}
}

func (fake *FakeGroupUpdater) UpdateGroupCallCount() int {
	fake.updateGroupMutex.RLock()
	defer fake.updateGroupMutex.RUnlock()
	return len(fake.updateGroupArgsForCall)
}

func (fake *FakeGroupUpdater) UpdateGroupCalls(stub func(context.Context, logr.Logger, string, ...status.UpdateRequest)) {
	fake.updateGroupMutex.Lock()
	defer fake.updateGroupMutex.Unlock()
	fake.UpdateGroupStub = stub
}

func (fake *FakeGroupUpdater) UpdateGroupArgsForCall(i int) (context.Context, logr.Logger, string, []status.UpdateRequest) {
	fake.updateGroupMutex.RLock()
	defer fake.updateGroupMutex.RUnlock()
	argsForCall := fake.updateGroupArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeGroupUpdater) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeGroupUpdater) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ status.GroupUpdater = new(FakeGroupUpdater)
