// Code generated by counterfeiter. DO NOT EDIT.
package staticfakes

import (
	"sync"

	v1 "k8s.io/api/core/v1"
	"k8s.io/apimachinery/pkg/types"
)

type FakeSecretStorer struct {
	DeleteStub        func()
	deleteMutex       sync.RWMutex
	deleteArgsForCall []struct {
	}
	GetNSNameStub        func() types.NamespacedName
	getNSNameMutex       sync.RWMutex
	getNSNameArgsForCall []struct {
	}
	getNSNameReturns struct {
		result1 types.NamespacedName
	}
	getNSNameReturnsOnCall map[int]struct {
		result1 types.NamespacedName
	}
	SetStub        func(*v1.Secret)
	setMutex       sync.RWMutex
	setArgsForCall []struct {
		arg1 *v1.Secret
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeSecretStorer) Delete() {
	fake.deleteMutex.Lock()
	fake.deleteArgsForCall = append(fake.deleteArgsForCall, struct {
	}{})
	stub := fake.DeleteStub
	fake.recordInvocation("Delete", []interface{}{})
	fake.deleteMutex.Unlock()
	if stub != nil {
		fake.DeleteStub()
	}
}

func (fake *FakeSecretStorer) DeleteCallCount() int {
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	return len(fake.deleteArgsForCall)
}

func (fake *FakeSecretStorer) DeleteCalls(stub func()) {
	fake.deleteMutex.Lock()
	defer fake.deleteMutex.Unlock()
	fake.DeleteStub = stub
}

func (fake *FakeSecretStorer) GetNSName() types.NamespacedName {
	fake.getNSNameMutex.Lock()
	ret, specificReturn := fake.getNSNameReturnsOnCall[len(fake.getNSNameArgsForCall)]
	fake.getNSNameArgsForCall = append(fake.getNSNameArgsForCall, struct {
	}{})
	stub := fake.GetNSNameStub
	fakeReturns := fake.getNSNameReturns
	fake.recordInvocation("GetNSName", []interface{}{})
	fake.getNSNameMutex.Unlock()
	if stub != nil {
		return stub()
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeSecretStorer) GetNSNameCallCount() int {
	fake.getNSNameMutex.RLock()
	defer fake.getNSNameMutex.RUnlock()
	return len(fake.getNSNameArgsForCall)
}

func (fake *FakeSecretStorer) GetNSNameCalls(stub func() types.NamespacedName) {
	fake.getNSNameMutex.Lock()
	defer fake.getNSNameMutex.Unlock()
	fake.GetNSNameStub = stub
}

func (fake *FakeSecretStorer) GetNSNameReturns(result1 types.NamespacedName) {
	fake.getNSNameMutex.Lock()
	defer fake.getNSNameMutex.Unlock()
	fake.GetNSNameStub = nil
	fake.getNSNameReturns = struct {
		result1 types.NamespacedName
	}{result1}
}

func (fake *FakeSecretStorer) GetNSNameReturnsOnCall(i int, result1 types.NamespacedName) {
	fake.getNSNameMutex.Lock()
	defer fake.getNSNameMutex.Unlock()
	fake.GetNSNameStub = nil
	if fake.getNSNameReturnsOnCall == nil {
		fake.getNSNameReturnsOnCall = make(map[int]struct {
			result1 types.NamespacedName
		})
	}
	fake.getNSNameReturnsOnCall[i] = struct {
		result1 types.NamespacedName
	}{result1}
}

func (fake *FakeSecretStorer) Set(arg1 *v1.Secret) {
	fake.setMutex.Lock()
	fake.setArgsForCall = append(fake.setArgsForCall, struct {
		arg1 *v1.Secret
	}{arg1})
	stub := fake.SetStub
	fake.recordInvocation("Set", []interface{}{arg1})
	fake.setMutex.Unlock()
	if stub != nil {
		fake.SetStub(arg1)
	}
}

func (fake *FakeSecretStorer) SetCallCount() int {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	return len(fake.setArgsForCall)
}

func (fake *FakeSecretStorer) SetCalls(stub func(*v1.Secret)) {
	fake.setMutex.Lock()
	defer fake.setMutex.Unlock()
	fake.SetStub = stub
}

func (fake *FakeSecretStorer) SetArgsForCall(i int) *v1.Secret {
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	argsForCall := fake.setArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeSecretStorer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.deleteMutex.RLock()
	defer fake.deleteMutex.RUnlock()
	fake.getNSNameMutex.RLock()
	defer fake.getNSNameMutex.RUnlock()
	fake.setMutex.RLock()
	defer fake.setMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeSecretStorer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
