// Code generated by counterfeiter. DO NOT EDIT.
package validationfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/state/validation"
)

type FakeAuthFieldsValidator struct {
	ValidateAuthZClaimNameStub        func(string) error
	validateAuthZClaimNameMutex       sync.RWMutex
	validateAuthZClaimNameArgsForCall []struct {
		arg1 string
	}
	validateAuthZClaimNameReturns struct {
		result1 error
	}
	validateAuthZClaimNameReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateAuthZClaimValueStub        func(string) error
	validateAuthZClaimValueMutex       sync.RWMutex
	validateAuthZClaimValueArgsForCall []struct {
		arg1 string
	}
	validateAuthZClaimValueReturns struct {
		result1 error
	}
	validateAuthZClaimValueReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateAuthZProxySetHeaderStub        func(string) error
	validateAuthZProxySetHeaderMutex       sync.RWMutex
	validateAuthZProxySetHeaderArgsForCall []struct {
		arg1 string
	}
	validateAuthZProxySetHeaderReturns struct {
		result1 error
	}
	validateAuthZProxySetHeaderReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCConfigURLStub        func(string) error
	validateOIDCConfigURLMutex       sync.RWMutex
	validateOIDCConfigURLArgsForCall []struct {
		arg1 string
	}
	validateOIDCConfigURLReturns struct {
		result1 error
	}
	validateOIDCConfigURLReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCFrontChannelLogoutURIStub        func(string) error
	validateOIDCFrontChannelLogoutURIMutex       sync.RWMutex
	validateOIDCFrontChannelLogoutURIArgsForCall []struct {
		arg1 string
	}
	validateOIDCFrontChannelLogoutURIReturns struct {
		result1 error
	}
	validateOIDCFrontChannelLogoutURIReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCIssuerStub        func(string) error
	validateOIDCIssuerMutex       sync.RWMutex
	validateOIDCIssuerArgsForCall []struct {
		arg1 string
	}
	validateOIDCIssuerReturns struct {
		result1 error
	}
	validateOIDCIssuerReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCLogoutURIStub        func(string) error
	validateOIDCLogoutURIMutex       sync.RWMutex
	validateOIDCLogoutURIArgsForCall []struct {
		arg1 string
	}
	validateOIDCLogoutURIReturns struct {
		result1 error
	}
	validateOIDCLogoutURIReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCPostLogoutURIStub        func(string) error
	validateOIDCPostLogoutURIMutex       sync.RWMutex
	validateOIDCPostLogoutURIArgsForCall []struct {
		arg1 string
	}
	validateOIDCPostLogoutURIReturns struct {
		result1 error
	}
	validateOIDCPostLogoutURIReturnsOnCall map[int]struct {
		result1 error
	}
	ValidateOIDCRedirectURIStub        func(string) error
	validateOIDCRedirectURIMutex       sync.RWMutex
	validateOIDCRedirectURIArgsForCall []struct {
		arg1 string
	}
	validateOIDCRedirectURIReturns struct {
		result1 error
	}
	validateOIDCRedirectURIReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimName(arg1 string) error {
	fake.validateAuthZClaimNameMutex.Lock()
	ret, specificReturn := fake.validateAuthZClaimNameReturnsOnCall[len(fake.validateAuthZClaimNameArgsForCall)]
	fake.validateAuthZClaimNameArgsForCall = append(fake.validateAuthZClaimNameArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateAuthZClaimNameStub
	fakeReturns := fake.validateAuthZClaimNameReturns
	fake.recordInvocation("ValidateAuthZClaimName", []interface{}{arg1})
	fake.validateAuthZClaimNameMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimNameCallCount() int {
	fake.validateAuthZClaimNameMutex.RLock()
	defer fake.validateAuthZClaimNameMutex.RUnlock()
	return len(fake.validateAuthZClaimNameArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimNameCalls(stub func(string) error) {
	fake.validateAuthZClaimNameMutex.Lock()
	defer fake.validateAuthZClaimNameMutex.Unlock()
	fake.ValidateAuthZClaimNameStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimNameArgsForCall(i int) string {
	fake.validateAuthZClaimNameMutex.RLock()
	defer fake.validateAuthZClaimNameMutex.RUnlock()
	argsForCall := fake.validateAuthZClaimNameArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimNameReturns(result1 error) {
	fake.validateAuthZClaimNameMutex.Lock()
	defer fake.validateAuthZClaimNameMutex.Unlock()
	fake.ValidateAuthZClaimNameStub = nil
	fake.validateAuthZClaimNameReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimNameReturnsOnCall(i int, result1 error) {
	fake.validateAuthZClaimNameMutex.Lock()
	defer fake.validateAuthZClaimNameMutex.Unlock()
	fake.ValidateAuthZClaimNameStub = nil
	if fake.validateAuthZClaimNameReturnsOnCall == nil {
		fake.validateAuthZClaimNameReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateAuthZClaimNameReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimValue(arg1 string) error {
	fake.validateAuthZClaimValueMutex.Lock()
	ret, specificReturn := fake.validateAuthZClaimValueReturnsOnCall[len(fake.validateAuthZClaimValueArgsForCall)]
	fake.validateAuthZClaimValueArgsForCall = append(fake.validateAuthZClaimValueArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateAuthZClaimValueStub
	fakeReturns := fake.validateAuthZClaimValueReturns
	fake.recordInvocation("ValidateAuthZClaimValue", []interface{}{arg1})
	fake.validateAuthZClaimValueMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimValueCallCount() int {
	fake.validateAuthZClaimValueMutex.RLock()
	defer fake.validateAuthZClaimValueMutex.RUnlock()
	return len(fake.validateAuthZClaimValueArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimValueCalls(stub func(string) error) {
	fake.validateAuthZClaimValueMutex.Lock()
	defer fake.validateAuthZClaimValueMutex.Unlock()
	fake.ValidateAuthZClaimValueStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimValueArgsForCall(i int) string {
	fake.validateAuthZClaimValueMutex.RLock()
	defer fake.validateAuthZClaimValueMutex.RUnlock()
	argsForCall := fake.validateAuthZClaimValueArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimValueReturns(result1 error) {
	fake.validateAuthZClaimValueMutex.Lock()
	defer fake.validateAuthZClaimValueMutex.Unlock()
	fake.ValidateAuthZClaimValueStub = nil
	fake.validateAuthZClaimValueReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZClaimValueReturnsOnCall(i int, result1 error) {
	fake.validateAuthZClaimValueMutex.Lock()
	defer fake.validateAuthZClaimValueMutex.Unlock()
	fake.ValidateAuthZClaimValueStub = nil
	if fake.validateAuthZClaimValueReturnsOnCall == nil {
		fake.validateAuthZClaimValueReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateAuthZClaimValueReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZProxySetHeader(arg1 string) error {
	fake.validateAuthZProxySetHeaderMutex.Lock()
	ret, specificReturn := fake.validateAuthZProxySetHeaderReturnsOnCall[len(fake.validateAuthZProxySetHeaderArgsForCall)]
	fake.validateAuthZProxySetHeaderArgsForCall = append(fake.validateAuthZProxySetHeaderArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateAuthZProxySetHeaderStub
	fakeReturns := fake.validateAuthZProxySetHeaderReturns
	fake.recordInvocation("ValidateAuthZProxySetHeader", []interface{}{arg1})
	fake.validateAuthZProxySetHeaderMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZProxySetHeaderCallCount() int {
	fake.validateAuthZProxySetHeaderMutex.RLock()
	defer fake.validateAuthZProxySetHeaderMutex.RUnlock()
	return len(fake.validateAuthZProxySetHeaderArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZProxySetHeaderCalls(stub func(string) error) {
	fake.validateAuthZProxySetHeaderMutex.Lock()
	defer fake.validateAuthZProxySetHeaderMutex.Unlock()
	fake.ValidateAuthZProxySetHeaderStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZProxySetHeaderArgsForCall(i int) string {
	fake.validateAuthZProxySetHeaderMutex.RLock()
	defer fake.validateAuthZProxySetHeaderMutex.RUnlock()
	argsForCall := fake.validateAuthZProxySetHeaderArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZProxySetHeaderReturns(result1 error) {
	fake.validateAuthZProxySetHeaderMutex.Lock()
	defer fake.validateAuthZProxySetHeaderMutex.Unlock()
	fake.ValidateAuthZProxySetHeaderStub = nil
	fake.validateAuthZProxySetHeaderReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateAuthZProxySetHeaderReturnsOnCall(i int, result1 error) {
	fake.validateAuthZProxySetHeaderMutex.Lock()
	defer fake.validateAuthZProxySetHeaderMutex.Unlock()
	fake.ValidateAuthZProxySetHeaderStub = nil
	if fake.validateAuthZProxySetHeaderReturnsOnCall == nil {
		fake.validateAuthZProxySetHeaderReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateAuthZProxySetHeaderReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCConfigURL(arg1 string) error {
	fake.validateOIDCConfigURLMutex.Lock()
	ret, specificReturn := fake.validateOIDCConfigURLReturnsOnCall[len(fake.validateOIDCConfigURLArgsForCall)]
	fake.validateOIDCConfigURLArgsForCall = append(fake.validateOIDCConfigURLArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCConfigURLStub
	fakeReturns := fake.validateOIDCConfigURLReturns
	fake.recordInvocation("ValidateOIDCConfigURL", []interface{}{arg1})
	fake.validateOIDCConfigURLMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCConfigURLCallCount() int {
	fake.validateOIDCConfigURLMutex.RLock()
	defer fake.validateOIDCConfigURLMutex.RUnlock()
	return len(fake.validateOIDCConfigURLArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCConfigURLCalls(stub func(string) error) {
	fake.validateOIDCConfigURLMutex.Lock()
	defer fake.validateOIDCConfigURLMutex.Unlock()
	fake.ValidateOIDCConfigURLStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCConfigURLArgsForCall(i int) string {
	fake.validateOIDCConfigURLMutex.RLock()
	defer fake.validateOIDCConfigURLMutex.RUnlock()
	argsForCall := fake.validateOIDCConfigURLArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCConfigURLReturns(result1 error) {
	fake.validateOIDCConfigURLMutex.Lock()
	defer fake.validateOIDCConfigURLMutex.Unlock()
	fake.ValidateOIDCConfigURLStub = nil
	fake.validateOIDCConfigURLReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCConfigURLReturnsOnCall(i int, result1 error) {
	fake.validateOIDCConfigURLMutex.Lock()
	defer fake.validateOIDCConfigURLMutex.Unlock()
	fake.ValidateOIDCConfigURLStub = nil
	if fake.validateOIDCConfigURLReturnsOnCall == nil {
		fake.validateOIDCConfigURLReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCConfigURLReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCFrontChannelLogoutURI(arg1 string) error {
	fake.validateOIDCFrontChannelLogoutURIMutex.Lock()
	ret, specificReturn := fake.validateOIDCFrontChannelLogoutURIReturnsOnCall[len(fake.validateOIDCFrontChannelLogoutURIArgsForCall)]
	fake.validateOIDCFrontChannelLogoutURIArgsForCall = append(fake.validateOIDCFrontChannelLogoutURIArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCFrontChannelLogoutURIStub
	fakeReturns := fake.validateOIDCFrontChannelLogoutURIReturns
	fake.recordInvocation("ValidateOIDCFrontChannelLogoutURI", []interface{}{arg1})
	fake.validateOIDCFrontChannelLogoutURIMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCFrontChannelLogoutURICallCount() int {
	fake.validateOIDCFrontChannelLogoutURIMutex.RLock()
	defer fake.validateOIDCFrontChannelLogoutURIMutex.RUnlock()
	return len(fake.validateOIDCFrontChannelLogoutURIArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCFrontChannelLogoutURICalls(stub func(string) error) {
	fake.validateOIDCFrontChannelLogoutURIMutex.Lock()
	defer fake.validateOIDCFrontChannelLogoutURIMutex.Unlock()
	fake.ValidateOIDCFrontChannelLogoutURIStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCFrontChannelLogoutURIArgsForCall(i int) string {
	fake.validateOIDCFrontChannelLogoutURIMutex.RLock()
	defer fake.validateOIDCFrontChannelLogoutURIMutex.RUnlock()
	argsForCall := fake.validateOIDCFrontChannelLogoutURIArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCFrontChannelLogoutURIReturns(result1 error) {
	fake.validateOIDCFrontChannelLogoutURIMutex.Lock()
	defer fake.validateOIDCFrontChannelLogoutURIMutex.Unlock()
	fake.ValidateOIDCFrontChannelLogoutURIStub = nil
	fake.validateOIDCFrontChannelLogoutURIReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCFrontChannelLogoutURIReturnsOnCall(i int, result1 error) {
	fake.validateOIDCFrontChannelLogoutURIMutex.Lock()
	defer fake.validateOIDCFrontChannelLogoutURIMutex.Unlock()
	fake.ValidateOIDCFrontChannelLogoutURIStub = nil
	if fake.validateOIDCFrontChannelLogoutURIReturnsOnCall == nil {
		fake.validateOIDCFrontChannelLogoutURIReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCFrontChannelLogoutURIReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuer(arg1 string) error {
	fake.validateOIDCIssuerMutex.Lock()
	ret, specificReturn := fake.validateOIDCIssuerReturnsOnCall[len(fake.validateOIDCIssuerArgsForCall)]
	fake.validateOIDCIssuerArgsForCall = append(fake.validateOIDCIssuerArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCIssuerStub
	fakeReturns := fake.validateOIDCIssuerReturns
	fake.recordInvocation("ValidateOIDCIssuer", []interface{}{arg1})
	fake.validateOIDCIssuerMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerCallCount() int {
	fake.validateOIDCIssuerMutex.RLock()
	defer fake.validateOIDCIssuerMutex.RUnlock()
	return len(fake.validateOIDCIssuerArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerCalls(stub func(string) error) {
	fake.validateOIDCIssuerMutex.Lock()
	defer fake.validateOIDCIssuerMutex.Unlock()
	fake.ValidateOIDCIssuerStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerArgsForCall(i int) string {
	fake.validateOIDCIssuerMutex.RLock()
	defer fake.validateOIDCIssuerMutex.RUnlock()
	argsForCall := fake.validateOIDCIssuerArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerReturns(result1 error) {
	fake.validateOIDCIssuerMutex.Lock()
	defer fake.validateOIDCIssuerMutex.Unlock()
	fake.ValidateOIDCIssuerStub = nil
	fake.validateOIDCIssuerReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCIssuerReturnsOnCall(i int, result1 error) {
	fake.validateOIDCIssuerMutex.Lock()
	defer fake.validateOIDCIssuerMutex.Unlock()
	fake.ValidateOIDCIssuerStub = nil
	if fake.validateOIDCIssuerReturnsOnCall == nil {
		fake.validateOIDCIssuerReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCIssuerReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURI(arg1 string) error {
	fake.validateOIDCLogoutURIMutex.Lock()
	ret, specificReturn := fake.validateOIDCLogoutURIReturnsOnCall[len(fake.validateOIDCLogoutURIArgsForCall)]
	fake.validateOIDCLogoutURIArgsForCall = append(fake.validateOIDCLogoutURIArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCLogoutURIStub
	fakeReturns := fake.validateOIDCLogoutURIReturns
	fake.recordInvocation("ValidateOIDCLogoutURI", []interface{}{arg1})
	fake.validateOIDCLogoutURIMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURICallCount() int {
	fake.validateOIDCLogoutURIMutex.RLock()
	defer fake.validateOIDCLogoutURIMutex.RUnlock()
	return len(fake.validateOIDCLogoutURIArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURICalls(stub func(string) error) {
	fake.validateOIDCLogoutURIMutex.Lock()
	defer fake.validateOIDCLogoutURIMutex.Unlock()
	fake.ValidateOIDCLogoutURIStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURIArgsForCall(i int) string {
	fake.validateOIDCLogoutURIMutex.RLock()
	defer fake.validateOIDCLogoutURIMutex.RUnlock()
	argsForCall := fake.validateOIDCLogoutURIArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURIReturns(result1 error) {
	fake.validateOIDCLogoutURIMutex.Lock()
	defer fake.validateOIDCLogoutURIMutex.Unlock()
	fake.ValidateOIDCLogoutURIStub = nil
	fake.validateOIDCLogoutURIReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCLogoutURIReturnsOnCall(i int, result1 error) {
	fake.validateOIDCLogoutURIMutex.Lock()
	defer fake.validateOIDCLogoutURIMutex.Unlock()
	fake.ValidateOIDCLogoutURIStub = nil
	if fake.validateOIDCLogoutURIReturnsOnCall == nil {
		fake.validateOIDCLogoutURIReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCLogoutURIReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCPostLogoutURI(arg1 string) error {
	fake.validateOIDCPostLogoutURIMutex.Lock()
	ret, specificReturn := fake.validateOIDCPostLogoutURIReturnsOnCall[len(fake.validateOIDCPostLogoutURIArgsForCall)]
	fake.validateOIDCPostLogoutURIArgsForCall = append(fake.validateOIDCPostLogoutURIArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCPostLogoutURIStub
	fakeReturns := fake.validateOIDCPostLogoutURIReturns
	fake.recordInvocation("ValidateOIDCPostLogoutURI", []interface{}{arg1})
	fake.validateOIDCPostLogoutURIMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCPostLogoutURICallCount() int {
	fake.validateOIDCPostLogoutURIMutex.RLock()
	defer fake.validateOIDCPostLogoutURIMutex.RUnlock()
	return len(fake.validateOIDCPostLogoutURIArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCPostLogoutURICalls(stub func(string) error) {
	fake.validateOIDCPostLogoutURIMutex.Lock()
	defer fake.validateOIDCPostLogoutURIMutex.Unlock()
	fake.ValidateOIDCPostLogoutURIStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCPostLogoutURIArgsForCall(i int) string {
	fake.validateOIDCPostLogoutURIMutex.RLock()
	defer fake.validateOIDCPostLogoutURIMutex.RUnlock()
	argsForCall := fake.validateOIDCPostLogoutURIArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCPostLogoutURIReturns(result1 error) {
	fake.validateOIDCPostLogoutURIMutex.Lock()
	defer fake.validateOIDCPostLogoutURIMutex.Unlock()
	fake.ValidateOIDCPostLogoutURIStub = nil
	fake.validateOIDCPostLogoutURIReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCPostLogoutURIReturnsOnCall(i int, result1 error) {
	fake.validateOIDCPostLogoutURIMutex.Lock()
	defer fake.validateOIDCPostLogoutURIMutex.Unlock()
	fake.ValidateOIDCPostLogoutURIStub = nil
	if fake.validateOIDCPostLogoutURIReturnsOnCall == nil {
		fake.validateOIDCPostLogoutURIReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCPostLogoutURIReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURI(arg1 string) error {
	fake.validateOIDCRedirectURIMutex.Lock()
	ret, specificReturn := fake.validateOIDCRedirectURIReturnsOnCall[len(fake.validateOIDCRedirectURIArgsForCall)]
	fake.validateOIDCRedirectURIArgsForCall = append(fake.validateOIDCRedirectURIArgsForCall, struct {
		arg1 string
	}{arg1})
	stub := fake.ValidateOIDCRedirectURIStub
	fakeReturns := fake.validateOIDCRedirectURIReturns
	fake.recordInvocation("ValidateOIDCRedirectURI", []interface{}{arg1})
	fake.validateOIDCRedirectURIMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURICallCount() int {
	fake.validateOIDCRedirectURIMutex.RLock()
	defer fake.validateOIDCRedirectURIMutex.RUnlock()
	return len(fake.validateOIDCRedirectURIArgsForCall)
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURICalls(stub func(string) error) {
	fake.validateOIDCRedirectURIMutex.Lock()
	defer fake.validateOIDCRedirectURIMutex.Unlock()
	fake.ValidateOIDCRedirectURIStub = stub
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURIArgsForCall(i int) string {
	fake.validateOIDCRedirectURIMutex.RLock()
	defer fake.validateOIDCRedirectURIMutex.RUnlock()
	argsForCall := fake.validateOIDCRedirectURIArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURIReturns(result1 error) {
	fake.validateOIDCRedirectURIMutex.Lock()
	defer fake.validateOIDCRedirectURIMutex.Unlock()
	fake.ValidateOIDCRedirectURIStub = nil
	fake.validateOIDCRedirectURIReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) ValidateOIDCRedirectURIReturnsOnCall(i int, result1 error) {
	fake.validateOIDCRedirectURIMutex.Lock()
	defer fake.validateOIDCRedirectURIMutex.Unlock()
	fake.ValidateOIDCRedirectURIStub = nil
	if fake.validateOIDCRedirectURIReturnsOnCall == nil {
		fake.validateOIDCRedirectURIReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.validateOIDCRedirectURIReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeAuthFieldsValidator) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAuthFieldsValidator) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ validation.AuthFieldsValidator = new(FakeAuthFieldsValidator)
