apiVersion: gateway.nginx.org/v1alpha1
kind: RateLimitPolicy
metadata:
  name: gateway-rate-limit
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: gateway
  rateLimit:
    local:
      rules:
      - zoneSize: 10m
        delay: 3
        noDelay: false
        burst: 5
        key: "$binary_remote_addr"
        rate: 10r/s
    dryRun: false
    logLevel: "info"
    rejectCode: 429
