// Code generated by counterfeiter. DO NOT EDIT.
package crdfakes

import (
	"sync"

	"github.com/nginx/nginx-gateway-fabric/v2/internal/controller/crd"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/rest"
)

type FakeChecker struct {
	CheckCRDsExistStub        func(*rest.Config, []schema.GroupVersionKind) (map[schema.GroupVersionKind]bool, error)
	checkCRDsExistMutex       sync.RWMutex
	checkCRDsExistArgsForCall []struct {
		arg1 *rest.Config
		arg2 []schema.GroupVersionKind
	}
	checkCRDsExistReturns struct {
		result1 map[schema.GroupVersionKind]bool
		result2 error
	}
	checkCRDsExistReturnsOnCall map[int]struct {
		result1 map[schema.GroupVersionKind]bool
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeChecker) CheckCRDsExist(arg1 *rest.Config, arg2 []schema.GroupVersionKind) (map[schema.GroupVersionKind]bool, error) {
	var arg2Copy []schema.GroupVersionKind
	if arg2 != nil {
		arg2Copy = make([]schema.GroupVersionKind, len(arg2))
		copy(arg2Copy, arg2)
	}
	fake.checkCRDsExistMutex.Lock()
	ret, specificReturn := fake.checkCRDsExistReturnsOnCall[len(fake.checkCRDsExistArgsForCall)]
	fake.checkCRDsExistArgsForCall = append(fake.checkCRDsExistArgsForCall, struct {
		arg1 *rest.Config
		arg2 []schema.GroupVersionKind
	}{arg1, arg2Copy})
	stub := fake.CheckCRDsExistStub
	fakeReturns := fake.checkCRDsExistReturns
	fake.recordInvocation("CheckCRDsExist", []interface{}{arg1, arg2Copy})
	fake.checkCRDsExistMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeChecker) CheckCRDsExistCallCount() int {
	fake.checkCRDsExistMutex.RLock()
	defer fake.checkCRDsExistMutex.RUnlock()
	return len(fake.checkCRDsExistArgsForCall)
}

func (fake *FakeChecker) CheckCRDsExistCalls(stub func(*rest.Config, []schema.GroupVersionKind) (map[schema.GroupVersionKind]bool, error)) {
	fake.checkCRDsExistMutex.Lock()
	defer fake.checkCRDsExistMutex.Unlock()
	fake.CheckCRDsExistStub = stub
}

func (fake *FakeChecker) CheckCRDsExistArgsForCall(i int) (*rest.Config, []schema.GroupVersionKind) {
	fake.checkCRDsExistMutex.RLock()
	defer fake.checkCRDsExistMutex.RUnlock()
	argsForCall := fake.checkCRDsExistArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeChecker) CheckCRDsExistReturns(result1 map[schema.GroupVersionKind]bool, result2 error) {
	fake.checkCRDsExistMutex.Lock()
	defer fake.checkCRDsExistMutex.Unlock()
	fake.CheckCRDsExistStub = nil
	fake.checkCRDsExistReturns = struct {
		result1 map[schema.GroupVersionKind]bool
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) CheckCRDsExistReturnsOnCall(i int, result1 map[schema.GroupVersionKind]bool, result2 error) {
	fake.checkCRDsExistMutex.Lock()
	defer fake.checkCRDsExistMutex.Unlock()
	fake.CheckCRDsExistStub = nil
	if fake.checkCRDsExistReturnsOnCall == nil {
		fake.checkCRDsExistReturnsOnCall = make(map[int]struct {
			result1 map[schema.GroupVersionKind]bool
			result2 error
		})
	}
	fake.checkCRDsExistReturnsOnCall[i] = struct {
		result1 map[schema.GroupVersionKind]bool
		result2 error
	}{result1, result2}
}

func (fake *FakeChecker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeChecker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ crd.Checker = new(FakeChecker)
