name: Conformance Testing

on:
  workflow_call:
    inputs:
      image:
        required: true
        type: string
      build-os:
        required: false
        type: string
        default: ''
      k8s-version:
        required: true
        type: string
      enable-experimental:
        required: true
        type: boolean
      enable-inference-extension:
        required: true
        type: boolean
      production-release:
        required: false
        type: boolean
        default: false
      release_version:
        required: false
        type: string
        default: ''

defaults:
  run:
    shell: bash

env:
  PLUS_USAGE_ENDPOINT: ${{ secrets.JWT_PLUS_REPORTING_ENDPOINT }}
  ENABLE_EXPERIMENTAL: ${{ inputs.enable-experimental }}
  ENABLE_INFERENCE_EXTENSION: ${{ inputs.enable-inference-extension }}

permissions:
  contents: read

jobs:
  conformance-tests:
    name: Run Tests
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.head.repo.fork || inputs.image != 'plus' }}
    permissions:
      contents: write # needed for uploading release artifacts
    env:
      DOCKER_BUILD_SUMMARY: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup conformance environment
        id: setup
        uses: ./.github/actions/conformance-setup
        with:
          image: ${{ inputs.image }}
          build-os: ${{ inputs.build-os }}
          k8s-version: ${{ inputs.k8s-version }}
          cluster-name: ${{ github.run_id }}
          production-release: ${{ inputs.production-release }}
          release_version: ${{ inputs.release_version }}
          nginx-crt: ${{ secrets.NGINX_CRT }}
          nginx-key: ${{ secrets.NGINX_KEY }}
          plus-license: ${{ secrets.JWT_PLUS_EXCEPTION_REPORTING }}

      - name: Run conformance tests
        run: |
          make run-conformance-tests CONFORMANCE_TAG=${{ github.sha }} NGF_VERSION=${{ github.ref_name }} CLUSTER_NAME=${{ github.run_id }}
          core_result=$(cat conformance-profile.yaml | yq '.profiles[0].core.result')
          extended_result=$(cat conformance-profile.yaml | yq '.profiles[0].extended.result')
          if [ "${core_result}" == "failure" ] || [ "${extended_result}" == "failure" ]; then echo "Conformance test failed, see above for details." && exit 2; fi
        working-directory: ./tests

      - name: Upload profile to GitHub
        if: ${{ inputs.enable-experimental }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: conformance-profile-${{ inputs.image }}-${{ inputs.k8s-version }}-${{ steps.setup.outputs.ngf-version }}
          path: ./tests/conformance-profile.yaml

      - name: Upload profile to release
        if: ${{ inputs.production-release && inputs.enable-experimental }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.release_version }} conformance-profile.yaml --clobber
        working-directory: ./tests

  inference-conformance-tests:
    name: Run Inference Tests
    runs-on: ubuntu-24.04
    if: ${{ !github.event.pull_request.head.repo.fork || inputs.image != 'plus' }}
    permissions:
      contents: write # needed for uploading release artifacts
    env:
      DOCKER_BUILD_SUMMARY: false
    steps:
      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup conformance environment
        id: setup
        uses: ./.github/actions/conformance-setup
        with:
          image: ${{ inputs.image }}
          build-os: ${{ inputs.build-os }}
          k8s-version: ${{ inputs.k8s-version }}
          cluster-name: ${{ github.run_id }}-inference
          production-release: ${{ inputs.production-release }}
          release_version: ${{ inputs.release_version }}
          nginx-crt: ${{ secrets.NGINX_CRT }}
          nginx-key: ${{ secrets.NGINX_KEY }}
          plus-license: ${{ secrets.JWT_PLUS_EXCEPTION_REPORTING }}

      - name: Run inference conformance tests
        run: |
          make run-inference-conformance-tests CONFORMANCE_TAG=${{ github.sha }} NGF_VERSION=${{ github.ref_name }} CLUSTER_NAME=${{ github.run_id }}-inference
          core_result=$(cat conformance-profile-inference.yaml | yq '.profiles[0].core.result')
          if [ "${core_result}" == "failure" ]; then echo "Inference Conformance test failed, see above for details." && exit 2; fi
        working-directory: ./tests

      - name: Upload profile to GitHub
        if: ${{ inputs.enable-experimental }} # add experimental flag to filter result upload
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: conformance-profile-inference-${{ inputs.image }}-${{ inputs.k8s-version }}-${{ steps.setup.outputs.ngf-version }}-${{ github.run_id }}
          path: ./tests/conformance-profile-inference.yaml

      - name: Upload profile to release
        if: ${{ inputs.production-release && inputs.enable-experimental }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${{ inputs.release_version }} conformance-profile-inference.yaml --clobber
        working-directory: ./tests
